export const contacts = [
  {
    image: '',
    name: 'Hodaya Chayu',
    phone: '0524569870',
    age: '22',
    address: 'Harav Vaeinrov 24 , Tirat Carmel',
    text: '',
    infoFlag: false,
    editFlag: false,
  },
  {
    image: '',
    name: 'Ezra chayu',
    phone: '0509906313',
    age: '28',
    address: 'Harav Mordechay Moshe 6, Tirat Carmel',
    text: '',
    infoFlag: false,
    editFlag: false,
  },
  {
    image: '',
    name: 'Shalom Cohen',
    phone: '0538875576',
    age: '35',
    address: 'Herzl 6, Haifa',
    text: '',
    infoFlag: false,
    editFlag: false,
  },
  {
    image: '',
    name: 'Nataly Dadon',
    phone: '0568734456',
    age: '40',
    address: 'Natan Elbaz 5 Jerusalem',
    text: '',
    infoFlag: false,
    editFlag: false,
  },
];
